name: Deploy YACO EXTRA API

on:
  workflow_dispatch:

permissions: 
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout OrnaCodexCrawler
        uses: actions/checkout@v4
        with: 
          repository: '67au/OrnaCodexCrawler'
          path: './crawler'
      - name: Checkout OrnaCodexExtra
        uses: actions/checkout@v4
        with: 
          repository: '67au/OrnaCodexExtra'
          path: './extra'
      - name: Setup Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.13
      - run: uv sync --directory ./crawler
      - name: Export Extra
        run: uv run --directory ./crawler main.py export_extra --extra ../extra/data --export ../template/extra
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./template/extra --project-name=${{ vars.CF_PAGES_EXTRA_NAME }}
